### ISSUE TITLE
Inaccessible field "java.util.Optional#value" in an object given to gson without a proper type adapter

### ISSUE THREAD

**Issue by maximilianpilz** [Draegerwerk/SDCcc#222]
I got the following exception, which is not expected, when running a test:

> com.google.gson.JsonIOException: Failed making field 'java.util.Optional#value' accessible; either increase its visibility or write a custom TypeAdapter for its declaring type.
See https://github.com/google/gson/blob/main/Troubleshooting.md#reflection-inaccessible
	at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:76) ~[gson-2.11.0.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:388) ~[gson-2.11.0.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:161) ~[gson-2.11.0.jar:?]
	at com.google.gson.Gson.getAdapter(Gson.java:628) ~[gson-2.11.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:57) ~[gson-2.11.0.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$2.write(ReflectiveTypeAdapterFactory.java:247) ~[gson-2.11.0.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:490) ~[gson-2.11.0.jar:?]
	at com.google.gson.Gson.toJson(Gson.java:944) ~[gson-2.11.0.jar:?]
	at com.google.gson.Gson.toJson(Gson.java:899) ~[gson-2.11.0.jar:?]
	at com.google.gson.Gson.toJson(Gson.java:848) ~[gson-2.11.0.jar:?]
	at com.google.gson.Gson.toJson(Gson.java:825) ~[gson-2.11.0.jar:?]
	at com.draeger.medical.sdccc.manipulation.GsonManipulationSerializer.serialize(GsonManipulationSerializer.kt:23) ~[classes/:?]
	at com.draeger.medical.sdccc.manipulation.GRpcManipulations.performCallWrapper(GRpcManipulations.java:391) ~[classes/:?]
	at com.draeger.medical.sdccc.manipulation.GRpcManipulations.createContextStateWithAssociation(GRpcManipulations.java:207) ~[classes/:?]

**Comment by maximilianpilz** [comment]
> [#241](https://github.com/Draegerwerk/SDCcc/pull/241) essentially fixed this issue, but the comment [#241 (comment)](https://github.com/Draegerwerk/SDCcc/pull/241#issuecomment-2706722535) still holds true.

The comment has been addressed by #246 .
